<a href="https://colab.research.google.com/github/SaeedAkhtar1/FDS_Lab/blob/main/ExpA9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A9.
Write a Python program to compute following computation on matrix: a) Addition of two matrices B) Subtraction of two matrices c) Multiplication of two matrices d) Transpose of a matrix

In [1]:
import numpy as np

In [2]:
matrix1=np.array([[1,3,5],[4,6,2],[3,9,5]])
matrix2=np.array([[3,5,6],[2,6,3],[2,5,3]])
print(matrix1)
print("\n")
print(matrix2)

[[1 3 5]
 [4 6 2]
 [3 9 5]]


[[3 5 6]
 [2 6 3]
 [2 5 3]]


In [3]:
#function to perform addition of matrices
def matrices_add(matrix1, matrix2):
    return np.add(matrix1, matrix2)
matrices_add(matrix1,matrix2)

array([[ 4,  8, 11],
       [ 6, 12,  5],
       [ 5, 14,  8]])

In [4]:
#function to perform subtraction of matrices
def matrices_sub(matrix1, matrix2):
    return np.subtract(matrix1, matrix2)
matrices_sub(matrix1, matrix2)

array([[-2, -2, -1],
       [ 2,  0, -1],
       [ 1,  4,  2]])

In [5]:
#function to perform multiplication of matrices
def matrices_multiplication(matrix1, matrix2):
    return np.dot(matrix1, matrix2)
matrices_multiplication(matrix1, matrix2)

array([[19, 48, 30],
       [28, 66, 48],
       [37, 94, 60]])

In [6]:
matrix1*matrix2

array([[ 3, 15, 30],
       [ 8, 36,  6],
       [ 6, 45, 15]])

In [7]:
#function to perform Transpose of matrix
def matrix_transpose(matrix):
    return np.transpose(matrix)
matrix_transpose(matrix1)


array([[1, 4, 3],
       [3, 6, 9],
       [5, 2, 5]])

In [8]:
matrix_transpose(matrix2)

array([[3, 2, 2],
       [5, 6, 5],
       [6, 3, 3]])